# Generated by Django 5.2.6 on 2025-11-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumo',
            name='texto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
